### ISSUE TITLE
Plugin error (IDE Fatal Error)

### ISSUE THREAD

**Issue by yzalert** [nvlad/yii2support#111]
Comments:
com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl cannot be cast to com.jetbrains.php.lang.psi.elements.ClassReference

Details:
com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl cannot be cast to com.jetbrains.php.lang.psi.elements.ClassReference
java.lang.ClassCastException: com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl cannot be cast to com.jetbrains.php.lang.psi.elements.ClassReference
	at com.nvlad.yii2support.objectfactory.ObjectFactoryUtils.getPhpClassInGridColumns(ObjectFactoryUtils.java:135)
	at com.nvlad.yii2support.objectfactory.ObjectFactoryUtils.findClassByArrayCreation(ObjectFactoryUtils.java:163)
	at com.nvlad.yii2support.objectfactory.ObjectFactoryMissedFieldInspection$1.visitPhpArrayCreationExpression(ObjectFactoryMissedFieldInspection.java:31)
	at com.jetbrains.php.lang.psi.elements.impl.ArrayCreationExpressionImpl.accept(ArrayCreationExpressionImpl.java:24)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:305)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by yzalert** [comment]
Hello, insperedia. Plugin does not work
