### ISSUE TITLE
Ошибка с getCurrentRootNamespace, DasNamespace

### ISSUE THREAD

**Issue by lgXenos** [nvlad/yii2support#130]
![img-2017-07-19-00-32-41](https://user-images.githubusercontent.com/14957311/28340843-e16c896e-6c19-11e7-9ab2-08443c522e41.png)

> com.intellij.database.model.DasModel.getCurrentRootNamespace()Lcom/intellij/database/model/DasNamespace;
java.lang.NoSuchMethodError: com.intellij.database.model.DasModel.getCurrentRootNamespace()Lcom/intellij/database/model/DasNamespace;
	at com.nvlad.yii2support.common.DatabaseUtils.getLookupItemsTables(DatabaseUtils.java:74)
	at com.nvlad.yii2support.database.QueryCompletionProvider.addCompletions(QueryCompletionProvider.java:132)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:135)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:128)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:817)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$1000(CompletionProgressIndicator.java:88)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:799)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:94)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:950)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:89)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by insperedia** [comment]
Could you please provide version of IDE?

**Comment by lgXenos** [comment]
PhpStorm 2016.1.1
Build #PS-145.970, built on May 3, 2016
JRE: 1.8.0_112-b15 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by insperedia** [comment]
Looks like plugin does not support this version and you need to update.
May be I will check this issue after I am ready current tasks.

**Comment by lgXenos** [comment]
> PhpStorm 2017.1.4
> Build #PS-171.4694.2, built on May 16, 2017
> JRE: 1.8.0_112-release-736-b21 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 7 6.1

All rigth
Полет нормальный на 2017м
