### ISSUE TITLE
SOE 

### ISSUE THREAD

**Issue by neuro159** [nvlad/yii2support#155]
tens of reports to our Exception Analyser Oct-Dec
java.lang.StackOverflowError
....
at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:145)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:145)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:145).....

**Comment by nvlad** [comment]
Thanks for reporting. 
Check new plugin release. SOE is repeating?
