### ISSUE TITLE
consistent null pointer exceptions on setting breakpoint conditions

### ISSUE THREAD

**Issue by narration-sd** [nvlad/yii2support#175]
### What steps will reproduce the problem?
- preparing Debug on PhpStorm
- set a breakpoint on code
- open the breakpoint to configure it
- enter a simple condition. Mine are usually `$someVar === 'somestring', usually no spaces in string

### What is the expected result?

Normal operation - the breakpoint is just set with condition added

### What do you get instead?
- The breakpoint indeed sets with the conditions, and works fine
- but a red Exception notification appears on PhpStorm
- opening the exception leads to you, with pic attached, and error/ stack trace presented as follows:

```null
java.lang.NullPointerException
    at com.nvlad.yii2support.objectfactory.ObjectFactoryCompletionProvider.getArrayCreation(ObjectFactoryCompletionProvider.java:83)
    at com.nvlad.yii2support.objectfactory.ObjectFactoryCompletionProvider.addCompletions(ObjectFactoryCompletionProvider.java:24)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:152)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
    at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:152)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:112)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.b(CompletionProgressIndicator.java:839)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$600(CompletionProgressIndicator.java:92)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:821)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
    at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:181)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:832)
    at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:108)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```
### Additional info

n.b. You'd get more and better reporting  if you fixed what JetBrains shows for your contact point to be this github -- right now it's pointing to a website with an empty nginx install, as you can see from attached picture.

![image](https://user-images.githubusercontent.com/247945/37695030-462f239a-2c89-11e8-8930-79d147b76872.png)

| Q                | A
| ---------------- | --------
| IDE Name        | PhpStorm
| IDE Version      |  several; current is 2018.1 Public Preview, Build #PS-181.4203.107
| Plugin version   |  0.8.42.5
| Yii App Template | basic / advanced

**Comment by insperedia** [comment]
Can not reproduce. Automated logging for NullPointerException is implemented
