### ISSUE TITLE
Index Yii2Support.ViewFileIndex deserialization violates equals / hashCode contract for Value parameter

### ISSUE THREAD

**Issue by chrkv** [nvlad/yii2support#183]
```
<< Index Yii2Support.ViewFileIndex deserialization violates equals / hashCode contract for Value parameter

java.lang.Throwable: Index Yii2Support.ViewFileIndex deserialization violates equals / hashCode contract for Value parameter
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.util.indexing.impl.MapReduceIndex.checkValuesHaveProperEqualsAndHashCode(MapReduceIndex.java:357)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:274)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:98)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:213)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1658)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$21(FileBasedIndexImpl.java:1586)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:523)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1545)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1533)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1512)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1676)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1673)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:76)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:46)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1695)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:720)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:874)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValueIterator(FileBasedIndexImpl.java:960)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:931)
	at com.intellij.util.indexing.FileBasedIndexImpl.getValues(FileBasedIndexImpl.java:782)
	at com.jetbrains.php.PhpIndexImpl.getChildNamespacesByParentName(PhpIndexImpl.java:251)
	at com.jetbrains.php.lang.psi.elements.impl.PhpNamespaceReferenceImpl$PhpNamespaceReferenceSegment.multiResolve(PhpNamespaceReferenceImpl.java:195)
	at com.jetbrains.php.lang.psi.elements.impl.PhpNamespaceReferenceImpl$PhpNamespaceReferenceSegment.isReferenceTo(PhpNamespaceReferenceImpl.java:253)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:52)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.lambda$execute$0(PsiSearchHelperImpl.java:763)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:139)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:226)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.execute(PsiSearchHelperImpl.java:759)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$1.processInReadAction(PsiSearchHelperImpl.java:212)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$1.processInReadAction(PsiSearchHelperImpl.java:196)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:927)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | 181.4445

**Comment by fjqtp** [comment]
Confirming this error. For me happened when upgraded from PHPstorm 2018.1.1 to 2018.1.2 EAP, after restart. Plugin version is 0.8.42.6.
But this error doesn't seem to interfere with plugin's activity, it works for me.

**Comment by Conwell** [comment]
Confirming this error for PhpStorm 2018.1.3 EAP. Plugin version is 0.8.42.6.

**Comment by Conwell** [comment]
Same error in PhpStorm 2018.2 EAP. Plugin version 0.9.50
Little more information - it's look like error while parsing textInput name attribute in view: 
```
<?= Html::textInput('timesheets[{{counter}}][timesheet.duration]', '{{inTimeFormat timesheet.duration}}',
    [
        'class' => 'form-control input-small-padding text-center day',
        'data-duration' => '{{#if timesheet.duration}}{{timesheet.duration}}{{else}}0{{/if}}',
        'data-day' => '{{day}}'
    ]); ?>
```
when change to 
```
<?= Html::textInput('timesheets[{{counter}}][Timesheet][duration]', '{{inTimeFormat timesheet.duration}}',
    [
        'class' => 'form-control input-small-padding text-center day',
        'data-duration' => '{{#if timesheet.duration}}{{timesheet.duration}}{{else}}0{{/if}}',
        'data-day' => '{{day}}'
    ]); ?>
```
got this error.
