### ISSUE TITLE
com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl cannot be cast to com.intellij.psi.PsiFile

### ISSUE THREAD

**Issue by nvlad** [nvlad/yii2support#19]
On rename DealPayment class to DealPaymentValidator
```
com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl cannot be cast to com.intellij.psi.PsiFile
java.lang.ClassCastException: com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl cannot be cast to com.intellij.psi.PsiFile
	at com.nvlad.yii2support.views.refactor.RenameViewProcessor.prepareRenaming(RenameViewProcessor.java:47)
	at com.intellij.refactoring.rename.RenameProcessor.prepareRenaming(RenameProcessor.java:130)
	at com.intellij.refactoring.rename.RenameProcessor.doRun(RenameProcessor.java:120)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenamer$MyRenameProcessor.doRun(MemberInplaceRenamer.java:319)
	at com.intellij.openapi.fileEditor.impl.NonProjectFileWritingAccessProvider.disableChecksDuring(NonProjectFileWritingAccessProvider.java:181)
	at com.intellij.refactoring.BaseRefactoringProcessor.run(BaseRefactoringProcessor.java:562)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenamer.performRenameInner(MemberInplaceRenamer.java:249)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenamer.a(MemberInplaceRenamer.java:218)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenamer.a(MemberInplaceRenamer.java:217)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:89)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:39)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:114)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:124)
	at com.intellij.openapi.application.TransactionGuardImpl$5.run(TransactionGuardImpl.java:270)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by kadanin-at-work** [comment]
+1
