### ISSUE TITLE
StackOverflowError is reported by user in this plugin

### ISSUE THREAD

**Issue by amaembo** [nvlad/yii2support#209]
Hello! IntelliJ IDEA developer here.

The following exception was reported by our user which is obviously caused by your plugin:
```
java.lang.StackOverflowError
	at com.intellij.psi.impl.PsiModificationTrackerImpl.getModificationCount(PsiModificationTrackerImpl.java:152)
	at com.intellij.psi.impl.PsiCachedValue.isDependencyOutOfDate(PsiCachedValue.java:70)
	at com.intellij.util.CachedValueBase.isUpToDate(CachedValueBase.java:128)
	at com.intellij.psi.impl.PsiCachedValue.isUpToDate(PsiCachedValue.java:65)
	at com.intellij.util.CachedValueBase.getUpToDateOrNull(CachedValueBase.java:107)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:214)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.jetbrains.php.lang.psi.PhpFileImpl.getTopLevelDefs(PhpFileImpl.java:206)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.resolveLocal(ClassReferenceImpl.java:234)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.resolveLocal(ClassReferenceImpl.java:204)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.getFQN(ClassReferenceImpl.java:344)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperFQN(PhpClassImpl.java:319)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperClass(PhpClassImpl.java:331)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
... (1200 rows like this skipped)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.common.ClassUtils.isClassInheritsOrEqual(ClassUtils.java:147)
	at com.nvlad.yii2support.properties.PropertiesInspection$1.visitElement(PropertiesInspection.java:41)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.visitPhpElement(PhpElementVisitor.java:36)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:70)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:276)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:244)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1156)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:65)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:247)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:218)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:121)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

IDE version: PhpStorm 182.4323.23; plugin version is unfortunately unavailable.

**Comment by insperedia** [comment]
Recursion limit is added
