### ISSUE TITLE
Ide freezes 

### ISSUE THREAD

**Issue by yujin1st** [nvlad/yii2support#233]
5 times in a row ide freezes in one place trying to autocompete one class
https://youtrack.jetbrains.com/issue/WI-48771 
devs from phpstorm said it's the plugin issue

**Comment by yujin1st** [comment]
[phpstorm-logs-20190919-131742.zip](https://github.com/nvlad/yii2support/files/3631941/phpstorm-logs-20190919-131742.zip)
![Снимок экрана 2019-09-19 в 13 20 08](https://user-images.githubusercontent.com/2317913/65256443-81932100-db3a-11e9-91c2-7c4e762220d7.png)
![Снимок экрана 2019-09-19 в 11 12 03](https://user-images.githubusercontent.com/2317913/65256444-822bb780-db3a-11e9-8e30-602531e3d218.png)
![Снимок экрана 2019-09-19 в 11 03 19](https://user-images.githubusercontent.com/2317913/65256445-822bb780-db3a-11e9-8100-6f52e05add8d.png)

**Comment by yujin1st** [comment]
`"ApplicationImpl pooled thread 899" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

	at com.intellij.psi.impl.source.PsiFileImpl.getContainingDirectory(PsiFileImpl.java:405)
	at com.intellij.psi.impl.source.PsiFileImpl.getParent(PsiFileImpl.java:399)
	at com.intellij.psi.impl.source.PsiFileImpl.getParent(PsiFileImpl.java:49)
	at com.nvlad.yii2support.common.ClassUtils.getPhpClass(ClassUtils.java:106)
	at com.nvlad.yii2support.common.ClassUtils.getPhpClassUniversal(ClassUtils.java:58)
	at com.nvlad.yii2support.objectfactory.ObjectFactoryUtils.findClassByArray(ObjectFactoryUtils.java:25)
	at com.nvlad.yii2support.objectfactory.ObjectFactoryUtils.findClassByArrayCreation(ObjectFactoryUtils.java:147)
	at com.nvlad.yii2support.objectfactory.ObjectFactoryCompletionProvider.addCompletions(ObjectFactoryCompletionProvider.java:60)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:40)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:150)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:148)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:141)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:77)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:40)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:150)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:119)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:55)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:824)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:809)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$5(CodeCompletionHandlerBase.java:326)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$$Lambda$4978/0x000000080264a440.run(Unknown Source)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.codeInsight.completion.AsyncCompletion$$Lambda$4979/0x000000080264a840.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1048)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:318)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$$Lambda$4975/0x0000000802649840.run(Unknown Source)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.codeInsight.completion.AsyncCompletion$$Lambda$4977/0x000000080264a040.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$445/0x0000000800599c40.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:592)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:538)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.codeInsight.completion.AsyncCompletion$$Lambda$4976/0x0000000802649c40.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:254)
	at java.base@11.0.4/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base@11.0.4/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.4/java.util.concurrent.ThreadPoolExecutor$Work
`

**Comment by i14a45** [comment]
+
https://youtrack.jetbrains.com/issue/WI-48980

**Comment by nvlad** [comment]
Hi! I publish test version with the bug fix, please test it - https://github.com/nvlad/yii2support/issues/239#issuecomment-563465859
