### ISSUE TITLE
Debug output causes freezes in production

### ISSUE THREAD

**Issue by donnerpeter** [nvlad/yii2support#236]
https://github.com/nvlad/yii2support/blob/281f2e23abb00946084c6f0060903c2517c42f15/src/com/nvlad/yii2support/views/index/ViewFileIndex.java#L140

Freeze for 180 seconds
IDE KILLED! Sampled time: 168600ms, sampling rate: 100ms, GC time: 107ms (0%), Class loading: 0%

The stack is from the thread that was blocking EDT

com.intellij.diagnostic.Freeze
	at java.base@11.0.4/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base@11.0.4/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at java.base@11.0.4/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base@11.0.4/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base@11.0.4/java.io.PrintStream.write(PrintStream.java:561)
	at java.base@11.0.4/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
	at java.base@11.0.4/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
	at java.base@11.0.4/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
	at java.base@11.0.4/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:184)
	at java.base@11.0.4/java.io.PrintStream.write(PrintStream.java:606)
	at java.base@11.0.4/java.io.PrintStream.print(PrintStream.java:745)
	at java.base@11.0.4/java.io.PrintStream.println(PrintStream.java:882)
	at com.nvlad.yii2support.views.index.ViewFileIndex$ViewInfoDataExternalizer.read(ViewFileIndex.java:140)
	at com.nvlad.yii2support.views.index.ViewFileIndex$ViewInfoDataExternalizer.read(ViewFileIndex.java:112)

**Comment by nvlad** [comment]
Hi! I publish test version with the bug fix, please test it - https://github.com/nvlad/yii2support/issues/239#issuecomment-563465859
