### ISSUE TITLE
IDE Fatal error

### ISSUE THREAD

**Issue by alxxxx** [nvlad/yii2support#262]
### What steps will reproduce the problem?
Плагин крашит Phpstorm при анализе файла.
Заметил такое поведение после обновления Phpstorm до последней версии и после того, как я начал объявлять типы аргументов функций и возвращаемых значений.

### What do you get instead?
`java.lang.UnsupportedOperationException: This PHP type is immutable
	at com.jetbrains.php.lang.psi.resolve.types.PhpType$ImmutablePhpType.getException(PhpType.java:1059)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType$ImmutablePhpType.add(PhpType.java:1038)
	at com.nvlad.yii2support.typeprovider.ActiveRecordTypeProvider.getBySignature(ActiveRecordTypeProvider.java:57)
	at com.nvlad.yii2support.typeprovider.ActiveRecordTypeProvider.getBySignature(ActiveRecordTypeProvider.java:67)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:730)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:602)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:176)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:122)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:101)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:632)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpArrayUsedOnlyForWriteInspection.arrayAssignmentByValue(PhpArrayUsedOnlyForWriteInspection.java:99)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpArrayUsedOnlyForWriteInspection$1.visitPhpAssignmentExpression(PhpArrayUsedOnlyForWriteInspection.java:34)
	at com.jetbrains.php.lang.psi.elements.impl.AssignmentExpressionImpl.accept(AssignmentExpressionImpl.java:35)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:66)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:298)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:267)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:266)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:266)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | Build #PS-203.5981.175, built on December 2, 2020
| Plugin version   | 0.10.57.33
| Yii App Template | basic

**Comment by nvlad** [comment]
Приветствую! Пришлите пожалуйста примеры кода после появления которого стала возникать эта ошибка.

Подобная проблема описана в issue #248, с одним из вариантов проблемного кода, может у вас есть другие примеры.

**Comment by alxxxx** [comment]
Вот подобный код отваливает плагин.

```php
namespace app\models;

use app\models\base\Example as BaseExample;
use yii\db\Query;

class Example extends BaseExample
{
	public static function getSomeData(string $param1, int $param2, string $param3)
	{
		$query = static::find();
		$query->select("x.*");
		$sub_query = (new Query())->select("y.name")->from("table y")->where(["=", "y.param", $param1]);
                $query->where(["param2" => $param3]);
		$query->andWhere(["not in", "x.name", $sub_query]);
		$query->orderBy(["priority" => SORT_DESC]);
		
		return $query->all();
	}
}
```

`java.lang.UnsupportedOperationException: This PHP type is immutable
	at com.jetbrains.php.lang.psi.resolve.types.PhpType$ImmutablePhpType.getException(PhpType.java:1059)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType$ImmutablePhpType.add(PhpType.java:1038)
	at com.nvlad.yii2support.typeprovider.ActiveRecordTypeProvider.getBySignature(ActiveRecordTypeProvider.java:57)
	at com.nvlad.yii2support.typeprovider.ActiveRecordTypeProvider.getBySignature(ActiveRecordTypeProvider.java:67)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:730)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:602)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:176)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:122)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:101)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:632)
	at com.jetbrains.php.lang.inspections.type.PhpIncompatibleReturnTypeInspection$1.checkReturnTypeCompatibility(PhpIncompatibleReturnTypeInspection.java:71)
	at com.jetbrains.php.lang.inspections.type.PhpIncompatibleReturnTypeInspection$1.visitPhpReturn(PhpIncompatibleReturnTypeInspection.java:52)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReturnImpl.accept(PhpReturnImpl.java:15)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:66)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:298)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:267)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:266)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:266)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1132)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1708)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1039)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:71)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:48)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:270)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:193)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:115)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

**Comment by alxxxx** [comment]
Ааа.. проблема аналогичная последнему посту из issue #248.

```php
namespace app\models;
use app\models\base\Example as BaseExample;
use yii\db\Query;

class Example extends BaseExample
{

	public static function getSomeData(string $param1, int $param2, string $param3)
	{
		$query = static::find();
		return $query->all();
	}
}
```

**Comment by nvlad** [comment]
Спасибо! Как появится время буду разбираться с происходящим

**Comment by PendalF89** [comment]
Здравствуйте!
Та же проблема, вот пример кода:
```php
public function actionUpdate()
{
        foreach (City::find()->all() as $city) {
              $sitemap = new Sitemap([
                  'domain' => Yii::$app->cityLoader->getHomepage($city->slug)
              ]);
              $sitemap->create(new ApkSitemap());
              $sitemap->createIndex();
	}
}
```

**Comment by abdouTurki** [comment]
Hello!
I'm facing the same issue, need to disable the plugin to get it to work again.

**Comment by marden** [comment]
+1 к проблеме, версия 2020.3 постоянно рапортует об ошибке плагина.

**Comment by nikitich** [comment]
+1 точно та же проблема, версия 2020.3.1

**Comment by zl939144892** [comment]
+1 same issue

**Comment by alxxxx** [comment]
Похоже плагин ушел в историю... А жаль, не плохой был плагин..

**Comment by PendalF89** [comment]
Кто-нибудь знает альтернативу?

**Comment by PendalF89** [comment]
> Похоже плагин ушел в историю... А жаль, не плохой был плагин..

Кто-нибудь знает альтернативу?

**Comment by nvlad** [comment]
Присоединяйтесь к разработке)

**Comment by iglooom** [comment]
Всем привет, я совершенно не спец по Java и тем более по написанию плагинов для идеи, просто подсмотрел как сделано у соседей в плагине для Symfony и переписал по аналогии кусок https://github.com/iglooom/yii2support/commit/adfe0db9ef4a112c3532dcf60b77a9cc97058375 
Не уверен что это правильный путь, но как минимум оно работает.
Может @nvlad как-то поправит и релизнет это дело )
В аттаче собранный вариант, надо только .zip поменять на .jar и заменить в соответствующей директории.
[yii2support-0.10.58.37.zip](https://github.com/nvlad/yii2support/files/6070636/yii2support-0.10.58.37.zip)

**Comment by nvlad** [comment]
Приветствую, @iglooom!
Делайте PR, гляну и сделаю релиз!)

PS: Тоже не специалист в Java, наверняка джависты и плагинописатели придут в ужас от кода плагина) главное что работает и порадует людей пользующихся плагином!)

**Comment by iglooom** [comment]
@nvlad готово )

**Comment by iglooom** [comment]
Такс, ну вот теперь вроде все. Починил косяк когда не работали подсказки вот в таких кейсах.
```php
$order = Orders::find()->one();
$order->account->
```

**Comment by nvlad** [comment]
> @nvlad готово )
> 
> PS: Хотя стоп, нашел косяк, к крашу то не приводит, но и не работает толком если что-то кроме find()->all() сделать. Постараюсь поправить, раз уже залез в это дело )

вот оно что, а то только хотел посмотреть, а PR пропал) Теперь гляну апдейт!) Спасибо

**Comment by nvlad** [comment]
Обновление опубликовано!)

**Comment by ldar** [comment]
Спасибо, чтоб воскресили плагин.
