### ISSUE TITLE
com.jetbrains.php.lang.psi.elements.impl.MethodImpl cannot be cast to com.jetbrains.php.lang.psi.ele

### ISSUE THREAD

**Issue by tongtoanbs** [nvlad/yii2support#53]
The plugin stops working for me, I don't know the reason
```
com.jetbrains.php.lang.psi.elements.impl.MethodImpl cannot be cast to com.jetbrains.php.lang.psi.elements.PhpClass
java.lang.ClassCastException: com.jetbrains.php.lang.psi.elements.impl.MethodImpl cannot be cast to com.jetbrains.php.lang.psi.elements.PhpClass
	at com.nvlad.yii2support.objectfactory.ObjectFactoryUtils.getClassByInstatiation(ObjectFactoryUtils.java:201)
	at com.nvlad.yii2support.objectfactory.ObjectFactoryUtils.findClassByArrayCreation(ObjectFactoryUtils.java:151)
	at com.nvlad.yii2support.objectfactory.ObjectFactoryUtils.getPhpClassByHash(ObjectFactoryUtils.java:173)
	at com.nvlad.yii2support.objectfactory.ObjectFactoryUtils.findClassByArrayCreation(ObjectFactoryUtils.java:163)
	at com.nvlad.yii2support.objectfactory.ObjectFactoryMissedFieldInspection$1.visitPhpArrayCreationExpression(ObjectFactoryMissedFieldInspection.java:33)
	at com.jetbrains.php.lang.psi.elements.impl.ArrayCreationExpressionImpl.accept(ArrayCreationExpressionImpl.java:24)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:304)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:123)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:212)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:141)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:212)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:141)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:212)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:141)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1055)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:61)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:315)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:225)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:131)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by rob006** [comment]
Same here. I'm working on Yii 1.1 project and this error occurs when I do anything in model class.

**Comment by awesomeguy3** [comment]
Same with new PhpStorm version.

**Comment by insperedia** [comment]
New version uploaded. Update plugin and give feedback if problem exists. Thanks.

**Comment by rob006** [comment]
It works fine for me, thx.

**Comment by tongtoanbs** [comment]
working fine for me, thanks.
